name: graphql_flutter_example
description: A Flutter project with GraphQL API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  fast_immutable_collections: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  graphql: ^5.0.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^4.10.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true